
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: Legacy
  version: '0.4.3' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Legacy, a javaFX 2D RPG
  description: |
    This game is an open source community game in the works.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  apps:
    launch:
      command: java -jar $SNAP/jar/Legacy-0.4.3.jar

  parts:
    java:
      # See 'snapcraft plugins'
      plugin: maven
      source: git://github.com/shyzus/Legacy.git
  
